name: Marinha Update Tweet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 tweepy

    - name: Fetch and Tweet Marinha Updates
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.API_KEY_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: |
        python - <<EOF
        import os
        import requests
        from bs4 import BeautifulSoup
        import tweepy
        from requests.adapters import HTTPAdapter
        from requests.packages.urllib3.poolmanager import PoolManager
        import ssl

        class TLSAdapter(HTTPAdapter):
            def init_poolmanager(self, *args, **kwargs):
                ctx = ssl.create_default_context()
                ctx.set_ciphers('DEFAULT@SECLEVEL=1')
                kwargs['ssl_context'] = ctx
                return super(TLSAdapter, self).init_poolmanager(*args, **kwargs)

        def get_marinha_updates():
          #  url = 'https://www.marinha.mil.br/chm/dados-do-smm-avisos-de-mau-tempo'
          #  s = requests.Session()
          #  s.mount('https://', TLSAdapter())
           # response = s.get(url)
           # if response.status_code != 200:
           #     print(f"Erro ao acessar {url}: {response.status_code}")
            #    return []
            #soup = BeautifulSoup(response.text, 'html.parser')
            # updates = soup.select('CSS_SELECTOR_DAS_ATUALIZACOES')
            return 'teste!!!'  # Pega as 5 primeiras atualizações

        def tweet_update(update):
            auth = tweepy.OAuthHandler(os.getenv('TWITTER_CONSUMER_KEY'), os.getenv('TWITTER_CONSUMER_SECRET'))
            auth.set_access_token(os.getenv('TWITTER_ACCESS_TOKEN'), os.getenv('TWITTER_ACCESS_TOKEN_SECRET'))
            api = tweepy.API(auth)
            api.update_status(update)
            print(f"Tweetado: {update}")

        updates = get_marinha_updates()
        if updates:
            for update in updates:
                try:
                    tweet_update(update)
                except Exception as e:
                    print(f"Erro ao postar no Twitter: {e}")
        else:
            print("Nenhuma atualização encontrada")
        EOF
